version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
  newman: postman/newman@0.0.2
jobs:
    build:
      executor: newman/postman-newman-docker
      steps:
        - checkout
        - newman/newman-run:
            collection: ./Users.postman_collection.json
            environment: ./e2e-test-PostMan-CircleCi.postman_environment.json


workflows:
  heroku_deploy:
     jobs:
       - build
       - heroku/deploy-via-git:
          requires:
           - build
            
           
    
            


        