version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
workflows:
  heroku_deploy:
    jobs:
       - heroku/deploy-via-git:
            auth:
              HEROKU_APP_NAME: $HEROKU_APP_NAME
              HEROKU_API_KEY: $HEROKU_API_KEY


        